language: ruby
cache:
- bundler
install:
- bundle install
rvm:
- 2.0
- 2.1
- 2.2
- 2.3.0
- 2.4.1
notifications:
  email:
    recipients:
    - sensu-plugin@sensu-plugins.io
    on_success: change
    on_failure: always
script:
- bundle exec rake default
- gem build sensu-plugins-mackerel.gemspec
- gem install sensu-plugins-mackerel-*.gem
deploy:
  provider: rubygems
  api_key:
    secure: gOZQwyDaLw8k7kY8wIKDyUGf0+Imsh5rv0pNVplywFDp1rMhCHFnnGGdkD7fqM67eMhF100rnmXFkBJjmfswZ0tr6R80CiUY/FHkUfuOfNKvDRA5gAAc/2kyoDumhBolHiIfEFEjV2o2TbwGI8CY//C1KTOx3PMblqzuwX1Qoq8=
  gem: sensu-plugins-mackerel
  on:
    tags: true
    all_branches: true
    rvm: 2.0
    rvm: 2.1
    rvm: 2.2
    rvm: 2.3.0
    rvm: 2.4.1
    repo: sensu-plugins/sensu-plugins-mackerel
